action_list = [
    'G1A2: nod head',
    'G2A2: bow',
    'G3A2: shake hands',
    'G4A2: rock-paper-scissors',
    'G5A2: touch elbows',
    'G6A2: wave hand',
    'G7A2: fist bumping',
    'G8A2: pat on shoulders',
    'G9A2: giving object',
    'G10A2: exchange object',
    'G11A2: clapping; hushing',
    'G12A2: drink water; brush teeth',
    'G13A2: stand up; jump up',
    'G14A2: take off a hat; play a phone',
    'G15A2: take a selfie; wipe face',
    'G16A2: cross hands in front; throat-slitting',
    'G17A2: crawling; open bottle',
    'G18A2: sneeze; yawn',
    'G19A2: self-cutting with knife; take off headphone',
    'G20A2: stretch oneself; flick hair',
    'G21A2: thumb up; thumb down',
    'G22A2: make ok sign; make victory sign',
    'G23A2: cutting nails; cutting paper',
    'G24A2: squat down; toss a coin',
    'G25A2: fold paper; ball up paper',
    'G26A2: play magic cube; surrender',
    'G27A2: apply cream on face; apply cream on hand',
    'G28A2: put on bag; take off bag',
    'G29A2: put object into bag; take object out of bag',
    'G30A2: open a box; yelling',
    'G31A2: arm circles; arm swings',
    'G32A2: whisper',
    'G33A2: clapping each other',
    'G34A2: running; vomiting',
    'G35A2: walk apart',
    'G36A2: headache; back pain',
    'G37A2: walk form apart to together',
    'G38A2: falling down; chest pain',
    'G39A2: support with arms;old people walking',
    'G40A2: cheers and drink',
    'G1A1: hit with knees',
    'G2A1: hit with head',
    'G3A1: punch to face',
    'G4A1: punch to body',
    'G5A1: cover mouth',
    'G6A1: strangling neck',
    'G7A1: slap',
    'G8A1: kicking',
    'G9A1: pushing',
    'G10A1: pierce arms',
    'G11A1: pull hairs',
    'G12A1: drag other person (other resist)',
    'G13A1: pull collar',
    'G14A1: shake others',
    'G15A1: beat with elbow',
    'G16A1: knock over',
    'G17A1: hit with object',
    'G18A1: point to person',
    'G19A1: lift ear',
    'G20A1: pinch arms',
    'G21A1: use cigarette to burn',
    'G22A1: sidekick person',
    'G23A1: pick and throw an object to person',
    'G24A1: shoot person',
    'G25A1: stab person',
    'G26A1: wave knife to others',
    'G27A1: splash liquid on person',
    'G28A1: stumble person',
    'G29A1: step on foot',
    'G30A1: pickpocketing',
    'G31A1: bite person',
    'G32A1: take picture for others (sneakily)',
    'G33A1: spiting to person',
    'G34A1: chop (cut) person',
    'G35A1: take chair while other sitting',
    'G36A1: hit the head with hand',
    'G37A1: pinch face with two hands',
    'G38A1: pinch body (not arm)',
    'G39A1: follow person',
    'G40A1: belt person'
]

# action_list = [
#     'hit with knees; nod head',
#     'hit with head; bow',
#     'punch to face; shake hands',
#     'punch to body; rock-paper-scissors',
#     'cover mouse; touch elbows',
#     'pinch neck; wave hand',
#     'slap; fist bumping',
#     'kicking; pat on back',
#     'pushing; giving object',
#     'pierce others; exchange object',
#     'pull hairs; clapping; hush',
#     'drag other person; drink water; brush teeth',
#     'pull collar; stand up; jump up',
#     'swing others; take off a hat; play a phone',
#     'beat with elbow; take a selfie; wipe face',
#     'knoch over; cross hands in front; throat-slitting',
#     'hit with object; crawling; open bottle',
#     'point to person; sneeze; yawn',
#     'cuff ear; self-cutting with knife; take off headphone',
#     'pinch arms; stretch oneself; flick hair',
#     'use cigarette to burn person; thumb up; thumb down',
#     'sidekick person; make ok sign; make victor sign',
#     'cast to person; cutting nails; cutting paper',
#     'shoot person; squat down; toss a coin',
#     'stab person; fold paper; ball up paper',
#     'wave knife to others; play magic cube; capitulate',
#     'splash liquid on person; apply cream on face; apply cream on hand',
#     'stumble person; put on bag; take off bag',
#     'step on foot; put object into bag; take object out of bag',
#     'touch pocket; open a box; yelling',
#     'bite person; arm circles; arm swings',
#     'take picture for others; whisper',
#     'split on person; clapping each other',
#     'chop person; running; vomiting',
#     'take other chair while sitting; walk apart',
#     'pat on head; headache, back pain',
#     'pinch face; walk toward',
#     'pinch body; falling down; chest pain',
#     'follow person; walk with person; shake fist',
#     'belt person; cheers and drink'
# ]
