# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_bone.npy
  label_path: ./data/ntu120/xsub/val_label.pkl
  debug: False

# model
model: model.msg3d.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph
  to_use_temporal_transformer: False
  section_size: 5
  # ablation
  ablation: sgcn_only

# test
phase: test
device: [0,1]
test_batch_size: 60
weights: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/results_csiro/20-11-29-ntu120_joint_xsub_only_sgcn_temp_trans_split_5/2020-11-29T23-02-52/weights/weights-best_model-44460.pt"

work_dir: ./work_dir/eval/20-11-28-ntu120_xsub_only_g3d_temp_trans
save_score: True