
work_dir: ./work_dir/21-09-08-ntu_xsub_2020_aaai_gcn_nas

# Feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /data/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/train_data_joint.npy
  label_path: /data/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /data/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/val_data_joint.npy
  label_path: /data/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/val_label.pkl
  debug: False

# Model
model: model.agcn3.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.AdjMatrixGraph
  graph_args:
    labeling_mode: 'spatial'

# Optim
weight_decay: 0.0005
base_lr: 0.05
step: [28,36,44,52]

# Training
num_epoch: 60
device: [0]
batch_size: 40
forward_batch_size: 40
test_batch_size: 40
nesterov: True
optimizer: SGD

# Input processing
to_add_onehot: False

# Pretrained models
# weights: "work_dir/20-12-09-ntu120_xsub_only_sgcn/2020-12-09T07-59-11/weights/weights-10-7500.pt"
# checkpoint: "work_dir/20-12-09-ntu120_xsub_only_sgcn/2020-12-09T07-59-11/checkpoints/checkpoint-10-fwbz42-7500.pt"
# resume: True

eval_start: 1
eval_interval: 5
