work_dir: ./work_dir/21-09-07-ntu_xsub_2019_cvpr_dgnn

model_saved_name: ./runs/ntu_cs_dgnn
# feeder
feeder: feeders.feeder_dgnn.Feeder
train_feeder_args:
  joint_data_path: /data/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/train_data_joint.npy
  bone_data_path: /data/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/train_data_bone.npy
  label_path: /data/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  joint_data_path: /data/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/val_data_joint.npy
  bone_data_path: /data/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/val_data_bone.npy
  label_path: /data/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/val_label.pkl

# model
model: model.dgnn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.directed_ntu_rgb_d.Graph
  # graph_args:
  #   labeling_mode: 'spatial'

# optim
weight_decay: 0.0005
base_lr: 0.1
step: [28,36,44,52]

# training
device: [0]
batch_size: 320
test_batch_size: 320
num_epoch: 60
nesterov: True
freeze_graph_until: 10  # Number of epochs until graphs can be updated
