#!/usr/bin/env bash

work_dir: ./work_dir/21-09-10-ntu_xsub_2020_cvpr_decouple_gcn_ste
#work_dir: ./work_dir/eval/20-12-09-ntu120_xsub_joint_bone_angle_only_sgcn

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: "/mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/train_ste_jnt_linear_8_w_orig.npy"
  label_path: "/mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/train_label.pkl"
  debug: False

test_feeder_args:
  data_path: "/mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/val_ste_jnt_linear_8_w_orig.npy"
  label_path: "/mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/val_label.pkl"
  debug: False

# model
model: model.decouple_gcn.Model
model_args:
  in_channels: 27
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  groups: 16
  block_size: 41
  graph_args:
    labeling_mode: 'spatial'

# optim
weight_decay: 0.0005
base_lr: 1e-3
step: [28,36,44,52]

# training
num_epoch: 60
device: [0]
batch_size: 4
forward_batch_size: 4
test_batch_size: 4
nesterov: True

# Additional
to_add_onehot: False

optimizer: SGD

# Pretrained models
#weights: "work_dir/21-05-06-ntu120_xsub_jnt_only_sgcn/2021-05-06T18-09-54/weights/weights-20-24142.pt"
#checkpoint: "work_dir/21-05-06-ntu120_xsub_jnt_only_sgcn/2021-05-06T18-09-54/checkpoints/checkpoint-20-fwbz42-24142.pt"
#resume: True

eval_start: 1
eval_interval: 5
