
work_dir: ./work_dir/21-09-19-frame_idx_regression_tte

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/train_data_jnt_tte_k_8.npy
  label_path: /mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/train_label.pkl
  debug: True
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/val_data_jnt_tte_k_8.npy
  label_path: /mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/val_label.pkl
  debug: True

# model
model: model.frame_idx_regressor.Model
model_args:
  in_channels: 27
  num_class: 60
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # transformers
  to_use_temporal_transformer: False

  # ablation
  ablation: sgcn_only

# optim
weight_decay: 0.0005
base_lr: 0.01
step: [28,36,44,52]

# training
num_epoch: 30
device: [0]
batch_size: 8
forward_batch_size: 8
test_batch_size: 16
nesterov: True

# 额外的
to_add_onehot: False
optimizer: Adam

# Pretrained models
#weights: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/work_dir/21-09-19-frame_idx_regression_tte/2021-09-19T19-50-40/weights/weights-30-360.pt"
#checkpoint: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/work_dir/21-09-19-frame_idx_regression_tte/2021-09-19T19-50-40/checkpoints/checkpoint-30-fwbz16-360.pt"
#resume: True

eval_start: 1
eval_interval: 1
