
work_dir: ./work_dir/test_sites/21_10_13-temp_cam

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: data/ntu120/xsub/train_data_joint.npy
  label_path: data/ntu120/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: data/ntu120/xsub/val_data_joint.npy
  label_path: data/ntu120/xsub/val_label.pkl
  debug: True

# model
model: model.test_model.Model
model_args:
  in_channels: 3
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # transformers
  to_use_temporal_transformer: False

  # ablation
  ablation: sgcn_only

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [28,36,44,52]

# test
phase: test
device: [0,1]
test_batch_size: 64
weights: "/media/zhenyue-qin/Backup Plus/Research/Skeleton-Based-Action-Recognition/Experiment-Records/Trigonometric/MSGCN/NTU120-XSub-Joint-Chron-Loss/weights/weights-epoch-best_model_100.pt"

# 额外的
to_add_onehot: False
optimizer: SGD

additional_loss:  # additional loss
    rank_pool: True
    rank_pool_w: 0.1
    rank_pool_start_epoch: 1