work_dir: ./work_dir/21-09-24-ntu120_xset_joint_2021_qin_msgcn_chron_0p1

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xset/train_data_joint.npy
  label_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xset/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xset/val_data_joint.npy
  label_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xset/val_label.pkl
  debug: False

# model
model: model.msg3d.Model
model_args:
  in_channels: 3
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # transformers
  to_use_temporal_transformer: False

  # ablation
  ablation: sgcn_only

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [50,70,90]

# training
num_epoch: 110
device: [0,1,2]
batch_size: 120
forward_batch_size: 120
test_batch_size: 240
nesterov: True

# 额外的
to_add_onehot: False
optimizer: SGD

# Additional
additional_loss:
    rank_pool: True
    rank_pool_w: 0.1
    rank_pool_start_epoch: 1

# Pretrained models
#weights: "work_dir/21-09-14-ntu120_xsub_2020_cvpr_msg3d_tte_k_3/2021-09-14T21-38-25/weights/weights-35-34685.pt"
#checkpoint: "work_dir/21-09-14-ntu120_xsub_2020_cvpr_msg3d_tte_k_3/2021-09-14T21-38-25/checkpoints/checkpoint-35-fwbz60-34685.pt"
#resume: True

eval_start: 1
eval_interval: 1
