
work_dir: ./work_dir/21-03-04-ntu120_xsub_jnt_lengthen_dct_only_sgcn

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /data1/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/train_data_joint.npy
  label_path: /data1/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False
  dct: lengthen # dct

test_feeder_args:
  data_path: /data1/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/val_data_joint.npy
  label_path: /data1/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/val_label.pkl
  dct: lengthen # dct

# model
model: model.msg3d.Model
model_args:
  in_channels: 28
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph
  frame_len: 450

  # transformers
  to_use_temporal_transformer: False

  # ablation
  ablation: sgcn_only

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [28,36,44,52]

# training
num_epoch: 60
device: [0,1]
batch_size: 60
forward_batch_size: 60
test_batch_size: 140
nesterov: True

# 额外的
to_add_onehot: True

optimizer: SGD

# Pretrained models
weights: "work_dir/21-03-04-ntu120_xsub_jnt_lengthen_dct_only_sgcn/2021-03-03T22-26-06/weights/weights-20-21000.pt"
checkpoint: "work_dir/21-03-04-ntu120_xsub_jnt_lengthen_dct_only_sgcn/2021-03-03T22-26-06/checkpoints/checkpoint-20-fwbz60-21000.pt"
resume: True

eval_start: 26
eval_interval: 1
