work_dir: ./work_dir/21_10_12-ntu120_xsub_bone-component_lab-msgcn  # saving path

feeder: feeders.feeder.Feeder  # training dataset arguments
train_feeder_args:
  data_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/train_data_bone.npy
  label_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:  # testing dataset arguments
  data_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/val_data_bone.npy
  label_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/val_label.pkl

model: model.component_lab.Model
model_args:
  in_channels: 3
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # transformers
  to_use_temporal_transformer: False

  # ablation
  ablation: sgcn_only


# optim
weight_decay: 0.0005
base_lr: 0.05
step: [28,36,44,52]

# training
num_epoch: 60
device: [0,1,2]
batch_size: 52
forward_batch_size: 52
test_batch_size: 150
nesterov: True

# 额外的
to_add_onehot: False
optimizer: SGD

# Pretrained models
#weights: "work_dir/21_10_12-ntu60_xsub_joint-component_lab-msgcn_T_600/2021-10-12T17-28-04/weights/weights-epoch-15.pt"
#checkpoint: "work_dir/21_10_12-ntu60_xsub_joint-component_lab-msgcn_T_600/2021-10-12T17-28-04/checkpoints/checkpoint-epoch-15.pt"
#resume: True

eval_start: 25
eval_interval: 5
