
work_dir: ./work_dir/21-06-06-ntu_xsub120_jnt_1ht_prtrn_tsfm

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: data/ntu120/xsub/train_data_joint_bone_angle_cangle_arms_legs.npy
  label_path: data/ntu120/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: data/ntu120/xsub/val_data_joint_bone_angle_cangle_arms_legs.npy
  label_path: data/ntu120/xsub/val_label.pkl
#  debug: False

# model
model: model.msg3d.Model
model_args:
  in_channels: 28
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # transformers
  is_using_pretrained_transformer: True

  # ablation
  ablation: sgcn_only

  # hyper convolution
#  hyper_conv: ntu


# optim
weight_decay: 0.0005
base_lr: 0.05
step: [50, 100, 150]
lr_decay: 0.1

# training
num_epoch: 200
device: [0,1,2]
batch_size: 30
forward_batch_size: 30
test_batch_size: 60
nesterov: True

# Additional
to_add_onehot: True
feature_combo: joint

optimizer: SGD

# Pretrained models
#weights: "work_dir/21-06-04-ntu_xsub120_jnt_1ht_prtrn_tsfm/2021-06-04T11-41-34/weights/weights-best_model_epoch_70-73500.pt"
#checkpoint: "work_dir/21-06-04-ntu_xsub120_jnt_1ht_prtrn_tsfm/2021-06-04T11-41-34/checkpoints/checkpoint-70-fwbz60-73500.pt"
#resume: True

eval_start: 10
eval_interval: 5

# test
# phase: test
# weights: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/results_dw_beijing/20-12-09-ntu120_xsub_joint_bone_angle_only_sgcn/2020-12-11T17-30-05/weights/weights-55-46200.pt"
# save_score: True
