
work_dir: ./work_dir/21-10-11_ntu120-xset-joint_2020_cvpr_msg3d-chron_tte_k_8

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xset/train_data_joint.npy
  label_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xset/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xset/val_data_joint.npy
  label_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xset/val_label.pkl

# model
model: model.msg3d.Model
model_args:
  in_channels: 27
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # transformers
  to_use_temporal_transformer: False

  # ablation
  ablation: original


# optim
weight_decay: 0.0005
base_lr: 0.05
step: [50,70,90]

# training
num_epoch: 110
device: [0,1,2]
batch_size: 64
forward_batch_size: 64
test_batch_size: 130
nesterov: True

# 额外的
to_add_onehot: False
optimizer: SGD

additional_loss:  # additional loss
    rank_pool: True
    rank_pool_w: 0.1
    rank_pool_start_epoch: 1

encoding_args:  # args for data encoding
  encode_type: trig_temp
  inc_type: linear
  freq_num: 8
  seq_len: 300

# Pretrained models
weights: "work_dir/21-10-11_ntu120-xset-joint_2020_cvpr_msg3d-chron_tte_k_8/2021-10-12T06-40-18/weights/weights-epoch-best_model_62.pt"
checkpoint: "work_dir/21-10-11_ntu120-xset-joint_2020_cvpr_msg3d-chron_tte_k_8/2021-10-12T06-40-18/checkpoints/checkpoint-epoch-best_model_62.pt"
resume: True

eval_start: 30
eval_interval: 1
