
work_dir: ./work_dir/21-06-04-trn_anu_jnt_msgcn
#work_dir: ./work_dir/eval/20-12-09-ntu120_xsub_joint_bone_angle_only_sgcn

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
#  data_path: data/ntu120/xsub/train_data_joint_bone_angle_cangle_arms_legs.npy
  data_path: /media/zhenyue-qin/Elements/Data-Collection/Skeleton-Data-Collection/data_processing/test_feeding_data/trn_data.npy
  label_path: /media/zhenyue-qin/Elements/Data-Collection/Skeleton-Data-Collection/data_processing/test_feeding_data/trn_label.pkl
  debug: False

test_feeder_args:
  data_path: /media/zhenyue-qin/Elements/Data-Collection/Skeleton-Data-Collection/data_processing/test_feeding_data/val_data.npy
  label_path: /media/zhenyue-qin/Elements/Data-Collection/Skeleton-Data-Collection/data_processing/test_feeding_data/val_label.pkl
#  debug: False

# model
model: model.msg3d.Model
model_args:
  in_channels: 3
  num_class: 80
  num_point: 32
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.azure_kinect.AdjMatrixGraph

  # ablation
  ablation: sgcn_only

# optim
weight_decay: 0.0005
base_lr: 0.001
step: [40, 50]

# training
num_epoch: 60
device: [0,1]
batch_size: 15
forward_batch_size: 15
test_batch_size: 30
nesterov: True

# Additional
to_add_onehot: False
feature_combo: joint

optimizer: SGD

# Pretrained models
weights: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/work_dir/21-06-04-trn_anu_jnt_msgcn/2021-06-05T19-25-26/weights/weights-best_model_epoch_15-11295.pt"
checkpoint: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/work_dir/21-06-04-trn_anu_jnt_msgcn/2021-06-05T19-25-26/checkpoints/checkpoint-15-fwbz15-11295.pt"
resume: True

eval_start: 5
eval_interval: 5

# test
# phase: test
# weights: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/results_dw_beijing/20-12-09-ntu120_xsub_joint_bone_angle_only_sgcn/2020-12-11T17-30-05/weights/weights-55-46200.pt"
# save_score: True
