work_dir: ./work_dir/recognition/ntu-xsub/AS_GCN

weights1: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/results_dw_beijing/21-09-07-ntu_xsub_2019_cvpr_as_gcn_aim/max_hop_4/lamda_05/epoch9_model1.pt"
weights2: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/results_dw_beijing/21-09-07-ntu_xsub_2019_cvpr_as_gcn_aim/max_hop_4/lamda_05/epoch9_model2.pt"

feeder: feeders.feeder_as_gcn.Feeder
train_feeder_args:
  data_path: "/mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/train_data_joint.npy"
  label_path: "/mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/train_label.pkl"
  random_move: True
  repeat_pad: True
  down_sample: True
test_feeder_args:
  data_path: "/mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/val_data_joint.npy"
  label_path: "/mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xsub/val_label.pkl"
  random_move: False
  repeat_pad: True
  down_sample: True

model1: model.as_gcn_2019_cvpr.as_gcn.Model
model1_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
    max_hop: 4

model2: model.as_gcn_2019_cvpr.utils.adj_learn.AdjacencyLearn
model2_args:
  n_in_enc: 150
  n_hid_enc: 128
  edge_types: 3
  n_in_dec: 3
  n_hid_dec: 128
  node_num: 25

weight_decay: 0.0001
base_lr1: 0.1
base_lr2: 0.0005
step: [28,36,44,52]

device: [0]
batch_size: 2
test_batch_size: 2
start_epoch: 10
num_epoch: 60
num_worker: 4

max_hop_dir: max_hop_4
lamda_act_dir: lamda_05
lamda_act: 0.5
