work_dir: ./work_dir/21-09-28-simple-st-test

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/train_data_joint.npy
  label_path: /mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/val_data_joint.npy
  label_path: /mnt/80F484E6F484E030/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/val_label.pkl
  debug: False

# model
model: model.simple_st.Model
model_args:
  in_channels: 27
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # transformers
  to_use_temporal_transformer: False

  # ablation
  ablation: sgcn_only

  is_get_cam: False  # CAM


# test
phase: test
device: [0,1]
test_batch_size: 256
weights: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/results_dw_beijing/21-09-28-simple-st-tte/2021-09-28T22-36-43/weights/weights-epoch-best_model_50.pt"

encoding_args:  # args for data encoding
  encode_type: trig_temp
  inc_type: linear
  freq_num: 8
  seq_len: 300

# 额外的
to_add_onehot: False
optimizer: SGD
