
work_dir: ./work_dir/21-07-28-trn_anu101_decouple-gcn_dct_enc_only
#work_dir: ./work_dir/eval/20-12-09-ntu120_xsub_joint_bone_angle_only_sgcn

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
#  data_path: data/ntu120/xsub/train_data_joint_bone_angle_cangle_arms_legs.npy
  data_path: /data1/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/anu-all/trn_data_jnt_dct_3_enc_only.npy
  label_path: data/anu-all/trn_label_all_action_front.pkl
  debug: False

test_feeder_args:
  data_path: /data1/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/anu-all/val_data_jnt_dct_3_enc_only.npy
  label_path: data/anu-all/val_label_all_action_back.pkl
  debug: False

# model
model: model.decouple_gcn.Model
model_args:
  in_channels: 9
  num_class: 102
  num_point: 32
  num_person: 2
  graph: graph.azure_kinect.Graph
  groups: 16
  graph_args:
    labeling_mode: 'spatial'

# optim
weight_decay: 0.0005
base_lr: 1e-3
step: [30]

# training
num_epoch: 60
device: [0,1,2]
batch_size: 80
forward_batch_size: 80
test_batch_size: 180
nesterov: True

# Additional
to_add_onehot: False

optimizer: Adam

# Pretrained models
#weights: "work_dir/21-05-06-ntu120_xsub_jnt_only_sgcn/2021-05-06T18-09-54/weights/weights-20-24142.pt"
#checkpoint: "work_dir/21-05-06-ntu120_xsub_jnt_only_sgcn/2021-05-06T18-09-54/checkpoints/checkpoint-20-fwbz42-24142.pt"
#resume: True

eval_start: 5
eval_interval: 5

# test
# phase: test
# weights: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/results_dw_beijing/20-12-09-ntu120_xsub_joint_bone_angle_only_sgcn/2020-12-11T17-30-05/weights/weights-55-46200.pt"
# save_score: True
