
work_dir: ./work_dir/21-08-31-trn_anubis_shift_gcn

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
#  data_path: data/ntu120/xsub/train_data_joint_bone_angle_cangle_arms_legs.npy
  data_path: "/data/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/anu-all/trn_data_all_action_front.npy"
  label_path: "/data/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/anu-all/trn_label_all_action_front.pkl"
  debug: False

test_feeder_args:
  data_path: "/data/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/anu-all/val_data_all_action_back.npy"
  label_path: "/data/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/anu-all/val_label_all_action_back.pkl"
  debug: False

# model
model: model.shift_gcn.Model
model_args:
  in_channels: 3
  num_class: 102
  num_point: 32
  num_person: 2
  graph: graph.azure_kinect.Graph
  graph_args:
    labeling_mode: 'spatial'

# optim
weight_decay: 0.0005
base_lr: 1e-3
step: [30]

# training
num_epoch: 60
device: [0,1,2]
batch_size: 70
forward_batch_size: 70
test_batch_size: 140
nesterov: True

# Additional
to_add_onehot: False

optimizer: SGD

eval_start: 5
eval_interval: 5

