
work_dir: ./work_dir/20-12-10-ntu120_xsub_bone_only_sgcn_sptl_tmp_trans_att

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu120/xsub/train_data_bone.npy
  label_path: ./data/ntu120/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_bone.npy
  label_path: ./data/ntu120/xsub/val_label.pkl
  debug: False

# model
model: model.msg3d.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # transformer temporal attention
  to_use_temporal_transformer: True
  temp_trans_joint_dim: 5
  section_sizes: [60, 30, 15]
  frame_norm: softmax

  # spatial transformer
  to_use_spatial_transformer: True

  # transformer temporal feature
  to_use_temp_trans_feature: False
  temp_trans_feature_n_head: 4
  temp_trans_feature_n_layer: 2

  # transformer spatial feature
  to_use_sptl_trans_feature: False
  sptl_trans_feature_n_head: 4
  sptl_trans_feature_n_layer: 2

  # ablation
  ablation: sgcn_only


# optim
weight_decay: 0.0005
base_lr: 0.05
step: [28, 36, 44, 52]

# training
num_epoch: 60
device: [0,1,2,3]
batch_size: 50
forward_batch_size: 50
test_batch_size: 50
nesterov: True

optimizer: SGD

# Pretrained models
weights: "./work_dir/20-12-10-ntu120_xsub_bone_only_sgcn_temp_trans_fea_h16_l_8/2020-12-10T19-12-29/weights/weights-5-5625.pt"
checkpoint: "./work_dir/20-12-10-ntu120_xsub_bone_only_sgcn_temp_trans_fea_h16_l_8/2020-12-10T19-12-29/checkpoints/checkpoint-5-fwbz56-5625.pt"
resume: True

eval_start: 24
eval_interval: 5
