
work_dir: ./work_dir/20-12-08-ntu120_xsub_joint_velocity_only_sgcn_temp_trans_end_tcn_sigmoid_10_10_5

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu120/xsub/train_data_joint_velocity.npy
  label_path: ./data/ntu120/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_joint_velocity.npy
  label_path: ./data/ntu120/xsub/val_label.pkl
  debug: False

# model
model: model.msg3d.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # transformers
  to_use_temporal_transformer: True
  temp_trans_joint_dim: 5
  section_sizes: [10, 10, 5]
  frame_norm: sigmoid

  # ablation
  ablation: sgcn_only


# optim
weight_decay: 0.0005
base_lr: 0.05
step: [30, 38, 46, 54]

# training
num_epoch: 60
device: [0,1,2,3]
batch_size: 56
forward_batch_size: 28
test_batch_size: 28
nesterov: True

optimizer: SGD

# Pretrained models
#weights: "./work_dir/20-12-04-ntu120_xsub_joint_velocity_only_sgcn_temp_trans_end_tcn_sigmoid/2020-12-04T14-51-02/weights/weights-30-6720.pt"
#checkpoint: "./work_dir/20-12-04-ntu120_xsub_joint_velocity_only_sgcn_temp_trans_end_tcn_sigmoid/2020-12-04T14-51-02/checkpoints/checkpoint-30-fwbz60-6720.pt"
#resume: True

eval_start: 5
eval_interval: 5
