
work_dir: ./work_dir/20-12-07-ntu120_xsub_bone_velocity_only_sgcn_temp_trans_30_15_5

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu120/xsub/train_data_bone_velocity.npy
  label_path: ./data/ntu120/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_bone_velocity.npy
  label_path: ./data/ntu120/xsub/val_label.pkl
  debug: False

# model
model: model.msg3d.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # transformers
  to_use_temporal_transformer: True
  temp_trans_joint_dim: 5
  section_sizes: [30, 15, 5]
  frame_norm: sigmoid

  # ablation
  ablation: sgcn_only


# optim
weight_decay: 0.0005
base_lr: 0.05
step: [28, 36, 44, 52]

# training
num_epoch: 60
device: [0,1]
batch_size: 56
forward_batch_size: 28
test_batch_size: 28
nesterov: True

optimizer: SGD

# Pretrained models
#weights: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/work_dir/20-12-04-ntu120_xsub_bone_velocity_only_sgcn_temp_trans_end_tcn_sigmoid/2020-12-04T08-00-33/weights/weights-25-30300.pt"
#checkpoint: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/work_dir/20-12-04-ntu120_xsub_bone_velocity_only_sgcn_temp_trans_end_tcn_sigmoid/2020-12-04T08-00-33/checkpoints/checkpoint-25-fwbz26-30300.pt"
#resume: True

eval_start: 5
eval_interval: 5
