
work_dir: ./work_dir/21-09-15-ntu120_xsub_2021_qin_msgcn_tte_k_3

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/train_trig_temp_enc_jnt_3_w_orig.npy
  label_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/val_trig_temp_enc_jnt_3_w_orig.npy
  label_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu120/xsub/val_label.pkl

# model
model: model.msg3d.Model
model_args:
  in_channels: 12
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # transformers
  to_use_temporal_transformer: False

  # ablation
  ablation: sgcn_only


# optim
weight_decay: 0.0005
base_lr: 0.05
step: [28,36,44,52]

# training
num_epoch: 60
device: [0,1,2,3]
batch_size: 160
forward_batch_size: 160
test_batch_size: 310
nesterov: True

# 额外的
to_add_onehot: False
optimizer: SGD

# Pretrained models
#weights: "work_dir/21-09-14-ntu120_xsub_2020_cvpr_msg3d_tte_k_3/2021-09-14T18-01-10/weights/weights-best_model_epoch_3-9453.pt"
#checkpoint: "work_dir/21-09-14-ntu120_xsub_2020_cvpr_msg3d_tte_k_3/2021-09-14T18-01-10/checkpoints/checkpoint-3-fwbz20-9453.pt"
#resume: True

eval_start: 5
eval_interval: 5
