
work_dir: ./work_dir/21-09-16-ntu60_xview_bone_2020_cvpr_msg3d_ste_k_3

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xview/train_ste_bon_linear_3_w_orig.npy
  label_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xview/val_ste_bon_linear_3_w_orig.npy
  label_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/ntu/xview/val_label.pkl

# model
model: model.msg3d.Model
model_args:
  in_channels: 12
  num_class: 60
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # transformers
  to_use_temporal_transformer: False

  # ablation
  ablation: original

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [30,40,50]

# training
num_epoch: 60
device: [0,1,2]
batch_size: 60
forward_batch_size: 60
test_batch_size: 120
nesterov: True

# 额外的
to_add_onehot: False
optimizer: SGD

# Pretrained models
#weights: "work_dir/21-09-14-ntu120_xsub_2020_cvpr_msg3d_tte_k_3/2021-09-14T21-38-25/weights/weights-35-34685.pt"
#checkpoint: "work_dir/21-09-14-ntu120_xsub_2020_cvpr_msg3d_tte_k_3/2021-09-14T21-38-25/checkpoints/checkpoint-35-fwbz60-34685.pt"
#resume: True

eval_start: 1
eval_interval: 5
