
work_dir: ./work_dir/21-01-02-ntu_xsub_joint_onehot_only_sgcn

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu/xsub/train_data_joint.npy
  label_path: ./data/ntu/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False
#  dct: lengthen # dct


test_feeder_args:
  data_path: ./data/ntu/xsub/val_data_joint.npy
  label_path: ./data/ntu/xsub/val_label.pkl
#  debug: False
  normalization: False
#  dct: lengthen # dct


# model
model: model.msg3d.Model
model_args:
  in_channels: 3
  num_class: 60
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # transformers
  to_use_temporal_transformer: False

  # ablation
  ablation: sgcn_only

  # Nerf and DCT
  nerf_dct_pip: True

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [28,36,44,52]

# training
num_epoch: 60
device: [0,1]
batch_size: 2
forward_batch_size: 2
test_batch_size: 4
nesterov: True

# Additional
to_add_onehot: False

optimizer: SGD

# Pretrained models
#weights: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/work_dir/21-03-03-ntu120_xsub_bon_normalize_xyz_only_sgcn/2021-03-03T12-01-47/weights/weights-30-59070.pt"
#checkpoint: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/work_dir/21-03-03-ntu120_xsub_bon_normalize_xyz_only_sgcn/2021-03-03T12-01-47/checkpoints/checkpoint-30-fwbz32-59070.pt"
#resume: True

eval_start: 27
eval_interval: 1

# test
# phase: test
# weights: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/results_dw_beijing/20-12-09-ntu120_xsub_joint_bone_angle_only_sgcn/2020-12-11T17-30-05/weights/weights-55-46200.pt"
# save_score: True
