
work_dir: ./work_dir/21-03-03-ntu120_xsub_bon_normalize_xyz_only_sgcn

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: data/ntu120/xsub/train_data_bone.npy
  label_path: data/ntu120/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: True

test_feeder_args:
  data_path: data/ntu120/xsub/val_data_bone.npy
  label_path: data/ntu120/xsub/val_label.pkl
  normalization: True

# model
model: model.msg3d.Model
model_args:
  in_channels: 28
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # transformers
  to_use_temporal_transformer: False

  # ablation
  ablation: sgcn_only


# optim
weight_decay: 0.0005
base_lr: 0.05
step: [28,36,44,52]

# training
num_epoch: 60
device: [0,1]
batch_size: 32
forward_batch_size: 32
test_batch_size: 70
nesterov: True

# 额外的
to_add_onehot: True

optimizer: SGD

# Pretrained models
# weights: "work_dir/20-12-09-ntu120_xsub_only_sgcn/2020-12-09T07-59-11/weights/weights-10-7500.pt"
# checkpoint: "work_dir/20-12-09-ntu120_xsub_only_sgcn/2020-12-09T07-59-11/checkpoints/checkpoint-10-fwbz42-7500.pt"
# resume: True

eval_start: 26
eval_interval: 1
