work_dir: ./work_dir/21-09-12-trn_anubis_frt_bck_2020_cvpr_shift_gcn_ste
Experiment_name: anubis-frt-bck

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: "/mnt/usb-Seagate_Expansion_Desk_NAABT50F-0:0-part2/Collected-Skeleton-Data-Backup/Skeleton-Data-Collection/data_processing/test_feeding_data/all-action-frt-bck/trn_data_all_action_front.npy"
  label_path: "/mnt/usb-Seagate_Expansion_Desk_NAABT50F-0:0-part2/Collected-Skeleton-Data-Backup/Skeleton-Data-Collection/data_processing/test_feeding_data/all-action-frt-bck/trn_label_all_action_front.pkl"
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: "/mnt/usb-Seagate_Expansion_Desk_NAABT50F-0:0-part2/Collected-Skeleton-Data-Backup/Skeleton-Data-Collection/data_processing/test_feeding_data/all-action-frt-bck/val_data_all_action_back.npy"
  label_path: "/mnt/usb-Seagate_Expansion_Desk_NAABT50F-0:0-part2/Collected-Skeleton-Data-Backup/Skeleton-Data-Collection/data_processing/test_feeding_data/all-action-frt-bck/val_label_all_action_back.pkl"
  debug: False

# model
model: model.shift_gcn.Model
model_args:
  in_channels: 3
  num_class: 102
  num_point: 32
  num_person: 2
  graph: graph.azure_kinect.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30,40]

# training
device: [0]
only_train_epoch: 0
batch_size: 2
test_batch_size: 2
num_epoch: 50
nesterov: True
