work_dir: ./work_dir/21-09-12-trn_anubis_frt_bck_2020_cvpr_shift_gcn
Experiment_name: anubis-frt-bck

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/anubis/frt-bck/train_data_joint.npy
  label_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/anubis/frt-bck/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/anubis/frt-bck/val_data_joint.npy
  label_path: /data_seoul/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/data/anubis/frt-bck/val_label.pkl
  debug: False

# model
model: model.shift_gcn.Model
model_args:
  in_channels: 3
  num_class: 102
  num_point: 32
  num_person: 2
  graph: graph.azure_kinect.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 1e-1
step: [5,10,20,30]

# training
device: [0]
only_train_epoch: 0
batch_size: 35
test_batch_size: 35
num_epoch: 50
nesterov: True
