
work_dir: ./work_dir/20-12-16-ntu120_xsub_joint_bone_angle_cangle_onehot_only_sgcn_subvideo_v20_o10

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
#  data_path: ./data/ntu120/xsub/train_data_bone.npy
  data_path: ./data/ntu120/xsub/train_data_joint_bone_angle_cangle.npy
  label_path: ./data/ntu120/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
#  data_path: ./data/ntu120/xsub/val_data_bone.npy
  data_path: ./data/ntu120/xsub/val_data_joint_bone_angle_cangle.npy
  label_path: ./data/ntu120/xsub/val_label.pkl

# model
model: model.msg3d.SubVideoTransformer
model_args:
  in_channels: 33
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

  # transformers
  to_use_temporal_transformer: False

  # ablation
  ablation: sgcn_only

  # subvideo
  video_len: 300
  subvideo_len: 20
  overlapping_len: 10
  to_subvideo_combine: "pooling"


# optim
weight_decay: 0.0005
base_lr: 0.05
step: [28,36,44,52]

# training
num_epoch: 60
device: [0,1,2,3]
batch_size: 40
forward_batch_size: 40
test_batch_size: 80
nesterov: True

# Additional
to_add_onehot: True

optimizer: SGD

# Pretrained models
#weights: "work_dir/20-12-14-ntu120_xsub_joint_bone_angle_cangle_onehot_only_sgcn_subvideo_v20_o10/2020-12-15T07-01-15/weights/weights-20-31500.pt"
#checkpoint: "work_dir/20-12-14-ntu120_xsub_joint_bone_angle_cangle_onehot_only_sgcn_subvideo_v20_o10/2020-12-15T07-01-15/checkpoints/checkpoint-20-fwbz40-31500.pt"
#resume: True

eval_start: 20
eval_interval: 5
