
work_dir: ./work_dir/21-01-07-kinetics_joint_bone_angle_cangle_arms_legs_head_velocity_only_sgcn

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /data1/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/Datasets/kinetics/train_data_joint_bone_angle_cangle_arms_legs_heads_velocity.npy
  label_path: /data1/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/Datasets/kinetics/train_label.pkl
  debug: False

test_feeder_args:
  data_path: /data1/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/Datasets/kinetics/val_data_joint_bone_angle_cangle_arms_legs_heads_velocity.npy
  label_path: /data1/zhenyue/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/Datasets/kinetics/val_label.pkl
#  debug: False

# model
model: model.msg3d.Model
model_args:
  in_channels: 33
  num_class: 400
  num_point: 18
  num_person: 2
  num_gcn_scales: 8    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 8
  graph: graph.kinetics.AdjMatrixGraph

  # transformers
  to_use_temporal_transformer: False

  # ablation
  ablation: sgcn_only


# optim
weight_decay: 0.0003
base_lr: 0.1
step: [18,28,38,48,58]

# training
num_epoch: 65
device: [0,1]
batch_size: 140
forward_batch_size: 140
test_batch_size: 280
nesterov: True

# Additional
to_add_onehot: True

optimizer: SGD

# Pretrained models
#weights: "work_dir/20-12-17-ntu120_xsub_joint_bone_angle_cangle_hands_2hands_only_sgcn/2020-12-20T13-17-20/weights/weights-59-9777.pt"
#checkpoint: "work_dir/20-12-17-ntu120_xsub_joint_bone_angle_cangle_hands_2hands_only_sgcn/2020-12-20T13-17-20/checkpoints/checkpoint-59-fwbz75-9777.pt"
#resume: True

eval_start: 5
eval_interval: 1

# test
# phase: test
# weights: "/media/zhenyue-qin/Backup Plus/Baseline-Implementation/Skeleton-Action-Recognition/2020-CVPR-Liu-MS-G3D/MS-G3D/results_dw_beijing/20-12-09-ntu120_xsub_joint_bone_angle_only_sgcn/2020-12-11T17-30-05/weights/weights-55-46200.pt"
# save_score: True
